### ISSUE TITLE
PC-side should treat RX and TX as asynchronous operations rather than sequential operations

### ISSUE THREAD

**Issue by tygamvrelis** [utra-robosoccer/soccer-communication#6]
**The issue**
After sending goal positions to the microcontroller, the PC-side script waits for the microcontroller to return sensor data. This makes RX and TX sequential operations. The microcontroller is capable of streaming back sensor data at a constant frequency while simultaneously receiving goal positions—it treats RX and TX as asynchronous operations. The PC-side script thus limits the capabilities of the PC-MCU communication.

**Desired behaviour**
- Microcontroller can stream data to PC and PC-side script will record it
- When the control systems need sensor data they can read it immediately from the cached PC-side data
- When the control systems have goal positions to send, the PC-side script can send it immediately to the microcontroller

This will likely require separate RX and TX threads

**Comment by rfairley** [comment]
Note: we want to get this done by around the time the Electrical team is done the Ethernet board.
